export const filterButtons = [
  "All",
  "JavaScript",
  "Music",
  "Gym",
  "News",
  "Gaming",
  "Artificial Intelligence",
  "Live",
  "T-series",
  "New-Age Music",
  "Comedy",
  "Indian soap operas",
  "Courses",
  "Game Shows",
  "DataBase",
  "webseries",
  "Algorithms",
  "Cooking",
];
